### ISSUE TITLE
Unknown block tag error with gulp-nunjucks-render 

### ISSUE THREAD

**Issue by matthewblewitt** [zephraph/nunjucks-markdown#25]
Hi

I'm getting this error when using `gulp-nunjucks-render`:

`events.js:160
      throw er; // Unhandled 'error' event
      ^
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: markdown
    at Object.exports.prettifyError (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/nunjucks/src/environment.js:472:27)
    at new_cls.renderString (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/nunjucks/src/environment.js:328:21)
    at Transform._transform (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/index.js:59:15)
    at Transform._read (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/gulp-nunjucks-render/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/issmbl/htdocs/test-nunjucks-md/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)`

My Gulp files is as follows:

`var gulp = require('gulp');
var nunjucksRender = require('gulp-nunjucks-render');
var markdown = require('nunjucks-markdown');
var marked = require('marked');

marked.setOptions({
    smartypants: false
});

gulp.task('default', function () {
    var env = nunjucksRender.nunjucks.configure(['templates']);
    markdown.register(env, marked);
    
    return gulp.src('templates/*.html')
        .pipe(nunjucksRender())
        .pipe(gulp.dest('dist'));
});`

Any suggestions would be greatly appreciated.

Thanks

**Comment by Webtransformer** [comment]
I have the same error.

**Comment by zephraph** [comment]
Thanks! Could I update the documentation to make it more clear?

**Comment by matthewblewitt** [comment]
That would be great, 'gulp-nunjucks-render' seems pretty popular and it would be nice to have an example I guess. Cheers
